hash-format = "sha256"

[[files]]
file = "LICENSE"

[[files]]
file = "config/craftpresence.json"

[[files]]
file = "config/fabric_loader_dependencies.json"

[[files]]
file = "config/fancymenu/assets/avatarhead-16.png"

[[files]]
file = "config/fancymenu/assets/cropped-32.png"

[[files]]
file = "config/fancymenu/assets/cropped-96.icns"

[[files]]
file = "config/fancymenu/custom_gui_screens.txt"

[[files]]
file = "config/fancymenu/customizablemenus.txt"

[[files]]
file = "config/fancymenu/customization/title_screen_layout.txt"

[[files]]
file = "config/fancymenu/layout_editor/widgets/element_layer_control.lewidget"

[[files]]
file = "config/fancymenu/legacy_checklist.txt"

[[files]]
file = "config/fancymenu/options.txt"

[[files]]
file = "config/fancymenu/ui_themes/cherry_blossom.json"

[[files]]
file = "config/fancymenu/ui_themes/cozy_campfire.json"

[[files]]
file = "config/fancymenu/ui_themes/dark.json"

[[files]]
file = "config/fancymenu/ui_themes/dark_high_contrast.json"

[[files]]
file = "config/fancymenu/ui_themes/light.json"

[[files]]
file = "config/fancymenu/ui_themes/light_high_contrast.json"

[[files]]
file = "config/fancymenu/ui_themes/pumpkin_soup.json"

[[files]]
file = "config/fancymenu/ui_themes/purple_void.json"

[[files]]
file = "config/fancymenu/ui_themes/spooky_season.json"

[[files]]
file = "config/fancymenu/user_variables.db"

[[files]]
file = "config/resourcepackoverrides.json"

[[files]]
file = "config/yosbr/config/appleskin.json5"

[[files]]
file = "config/yosbr/config/armor_hud.json"

[[files]]
file = "config/yosbr/config/betterhurtcam.toml"

[[files]]
file = "config/yosbr/config/c2me.toml"

[[files]]
file = "config/yosbr/config/capes.json5"

[[files]]
file = "config/yosbr/config/custom-hud/config.json"

[[files]]
file = "config/yosbr/config/custom-hud/profile1.txt"

[[files]]
file = "config/yosbr/config/durabilityviewer.json"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"

[[files]]
file = "config/yosbr/config/entityculling.json"

[[files]]
file = "config/yosbr/config/exordium.json"

[[files]]
file = "config/yosbr/config/fastload.properties"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"

[[files]]
file = "config/yosbr/config/healthindicator.toml"

[[files]]
file = "config/yosbr/config/ias.json"

[[files]]
file = "config/yosbr/config/inspecio.json"

[[files]]
file = "config/yosbr/config/inventoryhud.json"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"

[[files]]
file = "config/yosbr/config/moreculling.toml"

[[files]]
file = "config/yosbr/config/multiconnect/config.json"

[[files]]
file = "config/yosbr/config/nowheel.toml"

[[files]]
file = "config/yosbr/config/numeralping.json"

[[files]]
file = "config/yosbr/config/potioncounter.toml"

[[files]]
file = "config/yosbr/config/shulkerboxtooltip.json5"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"

[[files]]
file = "config/yosbr/config/sodium-options.json"

[[files]]
file = "config/yosbr/config/threadtweak.json"

[[files]]
file = "config/yosbr/config/totemcounter.toml"

[[files]]
file = "config/yosbr/config/vmp.properties"

[[files]]
file = "config/yosbr/config/xaerominimap-common.txt"

[[files]]
file = "config/yosbr/config/xaerominimap.txt"

[[files]]
file = "config/yosbr/config/zoomify.json"

[[files]]
file = "config/yosbr/debug-profile.json"

[[files]]
file = "config/yosbr/options.txt"

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/betterhurtcam.pw.toml"
metafile = true

[[files]]
file = "mods/bettershields.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-hud-forge.pw.toml"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/nowheel.pw.toml"
metafile = true

[[files]]
file = "mods/numeral-ping.pw.toml"
metafile = true

[[files]]
file = "mods/potioncounter.pw.toml"
metafile = true

[[files]]
file = "mods/resource-pack-overrides.pw.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/tiertagger.pw.toml"
metafile = true

[[files]]
file = "mods/totemcounter.pw.toml"
metafile = true

[[files]]
file = "mods/ukulib.pw.toml"
metafile = true

[[files]]
file = "mods/ukus-armor-hud.pw.toml"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
metafile = true

[[files]]
file = "mods/whoami.pw.toml"
metafile = true

[[files]]
file = "mods/why-am-i-on-fire.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/TheArtOfSaturation.zip"

[[files]]
file = "resourcepacks/uku3lig-Totem-pv9.zip"

[[files]]
file = "resourcepacks/ukupvp-resources.pw.toml"
metafile = true
