hash-format = "sha256"

[[files]]
file = "LICENSE"

[[files]]
file = "config/craftpresence.json"

[[files]]
file = "config/isxander-main-menu-credits.json"

[[files]]
file = "config/quilt-loader-overrides.json"

[[files]]
file = "config/yosbr/config/appleskin.json5"

[[files]]
file = "config/yosbr/config/armor_hud.json"

[[files]]
file = "config/yosbr/config/betterhurtcam.toml"

[[files]]
file = "config/yosbr/config/capes.json5"

[[files]]
file = "config/yosbr/config/custom-hud/config.json"

[[files]]
file = "config/yosbr/config/custom-hud/profile1.txt"

[[files]]
file = "config/yosbr/config/durabilityviewer.json"

[[files]]
file = "config/yosbr/config/healthindicator.toml"

[[files]]
file = "config/yosbr/config/inspecio.json"

[[files]]
file = "config/yosbr/config/inventoryhud.json"

[[files]]
file = "config/yosbr/config/multiconnect/config.json"

[[files]]
file = "config/yosbr/config/nowheel.toml"

[[files]]
file = "config/yosbr/config/potioncounter.toml"

[[files]]
file = "config/yosbr/config/shulkerboxtooltip.json5"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"

[[files]]
file = "config/yosbr/config/sodium-options.json"

[[files]]
file = "config/yosbr/config/totemcounter.toml"

[[files]]
file = "config/yosbr/config/xaerominimap.txt"

[[files]]
file = "config/yosbr/config/xaerominimap_entities.json"

[[files]]
file = "config/yosbr/config/xaeropatreon.txt"

[[files]]
file = "config/yosbr/options.txt"

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/betterhurtcam.pw.toml"
metafile = true

[[files]]
file = "mods/bettershields.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-hud-forge.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
metafile = true

[[files]]
file = "mods/mixin-conflict-helper.pw.toml"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/nowheel.pw.toml"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
metafile = true

[[files]]
file = "mods/potioncounter.pw.toml"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
metafile = true

[[files]]
file = "mods/totemcounter.pw.toml"
metafile = true

[[files]]
file = "mods/ukulib.pw.toml"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/whoami.pw.toml"
metafile = true

[[files]]
file = "mods/whyamionfire.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap-fair-play-edition.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/TheArtOfSaturation.zip"

[[files]]
file = "resourcepacks/uku3lig-Totem-pv9.zip"
