name = "ukus-pvp-modpack"
author = "uku"
version = "1.0.1+mc1.19.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.19.3"
quilt = "0.17.10"

[options]
no-internal-hashes = true
