name = "ukus-pvp-modpack"
author = "uku"
version = "0.0.6+mc1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67cac72214cee9af5e196bba1791e6df940eb417ab64359968095b575f7e3dc9"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
