name = "uku's pvp modpack"
author = "uku"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ed3cb6ad448e3f8c99cfcfe1321f6c486480c1d0dd3c210798e10d42e559c9f"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1"
