name = "ukus-pvp-modpack"
author = "uku"
version = "0.0.4+mc1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3eef7c6741599f0e4106e9b0578d072b73c3cee0924911661d45a251f2c94357"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
