name = "ukus-pvp-modpack"
author = "uku"
version = "0.1.3+mc1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea36f59622fac1851b3c7b2da37c7af20c98bde7135a22a3d0ed0c5dabe86642"

[versions]
minecraft = "1.19.3"
quilt = "0.17.8"
