name = "ukus-pvp-modpack"
author = "uku"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7717ab2b502b6a7a0485a0277dcbb753b1d131750747281285f6f48dee084161"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1"
