name = "ukus-pvp-modpack"
author = "uku"
version = "0.0.5+mc1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe785abdd0e731715e314896224b2b6862f117c21208fae4a7d6970c10286d45"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
