name = "ukus-pvp-modpack"
author = "uku"
version = "0.0.4+mc1.18.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4dd516b23df856b1edfb118b8d2a84dd9ec2cd25bfd007a122c3f5375c06f11"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
