name = "ukus-pvp-modpack"
author = "uku"
version = "1.4.0-beta.1+mc1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"

[options]
no-internal-hashes = true
