name = "ukus-pvp-modpack"
author = "uku"
version = "1.4.0+mc1.20.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.15.5"
minecraft = "1.20.4"

[options]
no-internal-hashes = true
